repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: spotless-check
        name: Code Format Verification (Spotless)
        entry: mvn spotless:apply
        language: system
        files: \.java$
        pass_filenames: false
