services:
  - type: web
    name: infopouch-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "true"
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_SMTP_AUTH
        value: "true"
      - key: MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
